# Generated by Django 3.2.11 on 2022-01-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
